# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infobox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_str', models.TextField()),
                ('json_str', models.TextField()),
                ('title', models.TextField()),
            ],
        ),
    ]
